package org.alipay.entity;
// Generated 2016-7-22 15:52:15 by Hibernate Tools 3.6.0.Final

import java.util.Date;

/**
 * Customer generated by hbm2java
 */
public class Customer {

	private Integer id;
	private String name;
	private Integer sex;
	private Date birthday;
	private String phoneNum;
	private String alternatePhoneNum;
	private String email;
	private String address;
	private String emergencyName;
	private String emergencyPhoneNum;
	private Integer isVip;
	private Integer rank;
	private Integer agentServicerId;
	private Integer certificateType;
	private String certificateNum;
	private String remark;
	private Integer isDeleted;
	private Date initTime;
	private String url;
	private Date entityVersion;
	private String uuid;

	public Customer() {
	}

	public Customer(Date entityVersion) {
		this.entityVersion = entityVersion;
	}

	public Customer(String name, Integer sex, Date birthday, String phoneNum, String alternatePhoneNum, String email,
			String address, String emergencyName, String emergencyPhoneNum, Integer isVip, Integer rank,
			Integer agentServicerId, Integer certificateType, String certificateNum, String remark, Integer isDeleted,
			Date initTime, String url, Date entityVersion, String uuid) {
		this.name = name;
		this.sex = sex;
		this.birthday = birthday;
		this.phoneNum = phoneNum;
		this.alternatePhoneNum = alternatePhoneNum;
		this.email = email;
		this.address = address;
		this.emergencyName = emergencyName;
		this.emergencyPhoneNum = emergencyPhoneNum;
		this.isVip = isVip;
		this.rank = rank;
		this.agentServicerId = agentServicerId;
		this.certificateType = certificateType;
		this.certificateNum = certificateNum;
		this.remark = remark;
		this.isDeleted = isDeleted;
		this.initTime = initTime;
		this.url = url;
		this.entityVersion = entityVersion;
		this.uuid = uuid;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Integer getSex() {
		return this.sex;
	}

	public void setSex(Integer sex) {
		this.sex = sex;
	}

	public Date getBirthday() {
		return this.birthday;
	}

	public void setBirthday(Date birthday) {
		this.birthday = birthday;
	}

	public String getPhoneNum() {
		return this.phoneNum;
	}

	public void setPhoneNum(String phoneNum) {
		this.phoneNum = phoneNum;
	}

	public String getAlternatePhoneNum() {
		return this.alternatePhoneNum;
	}

	public void setAlternatePhoneNum(String alternatePhoneNum) {
		this.alternatePhoneNum = alternatePhoneNum;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	public String getEmergencyName() {
		return this.emergencyName;
	}

	public void setEmergencyName(String emergencyName) {
		this.emergencyName = emergencyName;
	}

	public String getEmergencyPhoneNum() {
		return this.emergencyPhoneNum;
	}

	public void setEmergencyPhoneNum(String emergencyPhoneNum) {
		this.emergencyPhoneNum = emergencyPhoneNum;
	}

	public Integer getIsVip() {
		return this.isVip;
	}

	public void setIsVip(Integer isVip) {
		this.isVip = isVip;
	}

	public Integer getRank() {
		return this.rank;
	}

	public void setRank(Integer rank) {
		this.rank = rank;
	}

	public Integer getAgentServicerId() {
		return this.agentServicerId;
	}

	public void setAgentServicerId(Integer agentServicerId) {
		this.agentServicerId = agentServicerId;
	}

	public Integer getCertificateType() {
		return this.certificateType;
	}

	public void setCertificateType(Integer certificateType) {
		this.certificateType = certificateType;
	}

	public String getCertificateNum() {
		return this.certificateNum;
	}

	public void setCertificateNum(String certificateNum) {
		this.certificateNum = certificateNum;
	}

	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	public Integer getIsDeleted() {
		return this.isDeleted;
	}

	public void setIsDeleted(Integer isDeleted) {
		this.isDeleted = isDeleted;
	}

	public Date getInitTime() {
		return this.initTime;
	}

	public void setInitTime(Date initTime) {
		this.initTime = initTime;
	}

	public String getUrl() {
		return this.url;
	}

	public void setUrl(String url) {
		this.url = url;
	}

	public Date getEntityVersion() {
		return this.entityVersion;
	}

	public void setEntityVersion(Date entityVersion) {
		this.entityVersion = entityVersion;
	}

	public String getUuid() {
		return this.uuid;
	}

	public void setUuid(String uuid) {
		this.uuid = uuid;
	}

	@Override
	public String toString() {
		return "Customer [id=" + id + ", name=" + name + ", sex=" + sex + ", birthday=" + birthday + ", phoneNum="
				+ phoneNum + ", alternatePhoneNum=" + alternatePhoneNum + ", email=" + email + ", address=" + address
				+ ", emergencyName=" + emergencyName + ", emergencyPhoneNum=" + emergencyPhoneNum + ", isVip=" + isVip
				+ ", rank=" + rank + ", agentServicerId=" + agentServicerId + ", certificateType=" + certificateType
				+ ", certificateNum=" + certificateNum + ", remark=" + remark + ", isDeleted=" + isDeleted
				+ ", initTime=" + initTime + ", url=" + url + ", entityVersion=" + entityVersion + ", uuid=" + uuid
				+ "]";
	}

	
	
}
