package org.alipay.entity;
// Generated 2016-7-20 9:48:04 by Hibernate Tools 3.6.0.Final

import java.util.Date;

/**
 * Mypackage generated by hbm2java
 */
public class Mypackage  {

	private Integer id;
	private String telNum;
	private Integer packageId;
	private Date createTime;
	private Date startTime;
	private Date endTime;
	private Integer packageType;
	private Integer chargingWay;
	private Integer userId;
	
	private Feepackage feepackage;

	public Mypackage() {
	}

	public Mypackage(String telNum, Integer packageId, Date createTime, Date startTime, Date endTime,
			Integer packageType, Integer chargingWay, Integer userId) {
		this.telNum = telNum;
		this.packageId = packageId;
		this.createTime = createTime;
		this.startTime = startTime;
		this.endTime = endTime;
		this.packageType = packageType;
		this.chargingWay = chargingWay;
		this.userId = userId;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getTelNum() {
		return this.telNum;
	}

	public void setTelNum(String telNum) {
		this.telNum = telNum;
	}

	public Integer getPackageId() {
		return this.packageId;
	}

	public void setPackageId(Integer packageId) {
		this.packageId = packageId;
	}

	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	public Date getStartTime() {
		return this.startTime;
	}

	public void setStartTime(Date startTime) {
		this.startTime = startTime;
	}

	public Date getEndTime() {
		return this.endTime;
	}

	public void setEndTime(Date endTime) {
		this.endTime = endTime;
	}

	public Integer getPackageType() {
		return this.packageType;
	}

	public void setPackageType(Integer packageType) {
		this.packageType = packageType;
	}

	public Integer getChargingWay() {
		return this.chargingWay;
	}

	public void setChargingWay(Integer chargingWay) {
		this.chargingWay = chargingWay;
	}

	public Integer getUserId() {
		return this.userId;
	}

	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	
	public Feepackage getFeepackage() {
		return feepackage;
	}

	public void setFeepackage(Feepackage feepackage) {
		this.feepackage = feepackage;
	}

	@Override
	public String toString() {
		return "Mypackage [id=" + id + ", telNum=" + telNum + ", packageId=" + packageId + ", createTime=" + createTime
				+ ", startTime=" + startTime + ", endTime=" + endTime + ", packageType=" + packageType
				+ ", chargingWay=" + chargingWay + ", userId=" + userId + ", feepackage=" + feepackage + "]";
	}
	
	
}
